export const CALCULATED_SERIES_LIMITS = Object.freeze({
  maximumDefinitionBytes: 256 * 1024,
  maximumDiagnostics: 128,
  maximumDisplayLabelCharacters: 96,
  maximumDocumentBytes: 4 * 1024 * 1024,
  maximumIdCharacters: 128,
  maximumInstancesPerWorkspacePane: 32,
  maximumMessageCharacters: 320,
  maximumMigrationBytes: 256 * 1024,
  maximumMigrationOperations: 32,
  maximumOutputPointsPerPlot: 20_000,
  maximumPlotGroupsPerDefinition: 8,
  maximumPlotsPerDefinition: 32,
  maximumPlotsPerGroup: 8,
  maximumPortableCollectionEntries: 128,
  maximumPortableDepth: 8,
  maximumReferenceLinesPerGroup: 16,
  maximumRegionsPerWorkspacePane: 8,
  maximumResultBytes: 16 * 1024 * 1024,
  maximumScaleGroupsPerRegion: 4,
  maximumTotalOutputPoints: 100_000,
  maximumUnresolvedInstanceBytes: 64 * 1024,
  maximumWorkspacePanes: 8,
});
