// PDA type registry for manual, session-scoped annotations.

export const OB_COLORS = Object.freeze({
  color: '#9e9e9e',
  fillColor: '#9e9e9e24',
  textColor: '#d1d4dc',
});

export const PDA_TYPES = {
  bsl: {
    id: 'bsl',
    label: 'BSL',
    shape: 'liquidity-line',
    color: '#26a69a',
    textColor: '#b2dfdb',
    priceField: 'high',
    labelPosition: 'above',
    objective: false,
    pointSet: false,
  },
  ssl: {
    id: 'ssl',
    label: 'SSL',
    shape: 'liquidity-line',
    color: '#ef5350',
    textColor: '#ffcdd2',
    priceField: 'low',
    labelPosition: 'below',
    objective: false,
    pointSet: false,
  },
  'wick-ce': {
    id: 'wick-ce',
    label: 'Wick CE',
    shape: 'liquidity-line',
    color: '#fbc02d',
    textColor: '#fff9c4',
    labelPosition: 'above',
    objective: false,
    pointSet: false,
  },
  fvg: {
    id: 'fvg',
    label: 'FVG',
    shape: 'range',
    color: '#ab47bc',
    objective: false,
    pointSet: false,
  },
  ifvg: {
    id: 'ifvg',
    label: 'IFVG',
    shape: 'range',
    color: '#b39ddb',
    textColor: '#ede7f6',
    objective: false,
    pointSet: false,
  },
  ob: {
    id: 'ob',
    label: 'OB',
    shape: 'range',
    color: OB_COLORS.color,
    textColor: OB_COLORS.textColor,
    objective: false,
    pointSet: false,
  },
  'ob-last-bar': {
    id: 'ob-last-bar',
    label: 'OB Last Bar',
    shape: 'liquidity-line',
    color: '#8a8f98',
    textColor: '#c4c8d0',
    labelPosition: 'above',
    objective: false,
    pointSet: false,
  },
  breaker: {
    id: 'breaker',
    label: 'Breaker',
    shape: 'range',
    color: '#ff7043',
    objective: false,
    pointSet: false,
  },
  fib: {
    id: 'fib',
    label: 'Fib',
    shape: 'fib-retracement',
    color: '#f0f3fa',
    textColor: '#d1d4dc',
    objective: false,
    pointSet: false,
  },
  ndog: {
    id: 'ndog',
    label: 'NDOG',
    shape: 'range',
    color: '#42a5f5',
    objective: true,
    pointSet: false,
  },
  nwog: {
    id: 'nwog',
    label: 'NWOG',
    shape: 'range',
    color: '#7e57c2',
    objective: true,
    pointSet: false,
  },
  eqh: {
    id: 'eqh',
    label: 'EQH',
    shape: 'point-set',
    color: '#26a69a',
    textColor: '#b2dfdb',
    priceField: 'high',
    labelPosition: 'above',
    objective: false,
    pointSet: true,
  },
  eql: {
    id: 'eql',
    label: 'EQL',
    shape: 'point-set',
    color: '#ef5350',
    textColor: '#ffcdd2',
    priceField: 'low',
    labelPosition: 'below',
    objective: false,
    pointSet: true,
  },
};

export function getPdaType(type) {
  return PDA_TYPES[type] || null;
}
